pilot:
  token: "45d0ad54-9606-494e-939f-4a58fc620f87"

experimental:
  localPlugins:
    analytics:
      moduleName: github.com/valist-io/analytics

api:
  dashboard: true
  insecure: true

entrypoints:
  http:
    address: ":3334"
    forwardedHeaders:
      insecure: true

providers:
  file:
    filename: rules-valist.yaml
